CREATE SCHEMA IF NOT EXISTS gaylemon_public;
CREATE SCHEMA IF NOT EXISTS gaylemon_ops;

CREATE TABLE IF NOT EXISTS gaylemon_ops.schema_migrations (
    version text PRIMARY KEY,
    applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gaylemon_ops.agents (
    agent_id text PRIMARY KEY,
    version text NOT NULL DEFAULT '',
    profile text NOT NULL DEFAULT 'jeu-prioritaire',
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    last_success_at timestamptz,
    queue_depth bigint NOT NULL DEFAULT 0,
    last_error text NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS gaylemon_ops.agent_stream_state (
    agent_id text NOT NULL REFERENCES gaylemon_ops.agents(agent_id) ON DELETE CASCADE,
    stream text NOT NULL,
    active_sequence bigint NOT NULL DEFAULT 0,
    source_revision text NOT NULL DEFAULT '',
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (agent_id, stream)
);

CREATE TABLE IF NOT EXISTS gaylemon_ops.ingest_nonces (
    agent_id text NOT NULL,
    nonce text NOT NULL,
    expires_at timestamptz NOT NULL,
    PRIMARY KEY (agent_id, nonce)
);
CREATE INDEX IF NOT EXISTS ingest_nonces_expires_at_idx ON gaylemon_ops.ingest_nonces(expires_at);

CREATE TABLE IF NOT EXISTS gaylemon_ops.ingest_batches (
    batch_id text PRIMARY KEY,
    agent_id text NOT NULL REFERENCES gaylemon_ops.agents(agent_id),
    stream text NOT NULL,
    schema_version integer NOT NULL,
    sequence bigint NOT NULL,
    source_revision text NOT NULL DEFAULT '',
    captured_at timestamptz NOT NULL,
    accepted_at timestamptz NOT NULL DEFAULT now(),
    body_sha256 text NOT NULL,
    status text NOT NULL,
    document_count integer NOT NULL DEFAULT 0,
    UNIQUE (agent_id, stream, sequence)
);
CREATE INDEX IF NOT EXISTS ingest_batches_accepted_at_idx ON gaylemon_ops.ingest_batches(accepted_at DESC);

CREATE TABLE IF NOT EXISTS gaylemon_ops.sync_runs (
    run_id bigserial PRIMARY KEY,
    batch_id text REFERENCES gaylemon_ops.ingest_batches(batch_id) ON DELETE SET NULL,
    agent_id text NOT NULL,
    stream text NOT NULL,
    captured_at timestamptz NOT NULL,
    accepted_at timestamptz NOT NULL DEFAULT now(),
    duration_ms bigint NOT NULL DEFAULT 0,
    cpu_user_ms bigint NOT NULL DEFAULT 0,
    cpu_system_ms bigint NOT NULL DEFAULT 0,
    max_rss_bytes bigint NOT NULL DEFAULT 0,
    io_read_bytes bigint NOT NULL DEFAULT 0,
    io_write_bytes bigint NOT NULL DEFAULT 0,
    bytes_read bigint NOT NULL DEFAULT 0,
    bytes_compressed bigint NOT NULL DEFAULT 0,
    bytes_sent bigint NOT NULL DEFAULT 0,
    status text NOT NULL DEFAULT 'success',
    message text NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS sync_runs_captured_at_idx ON gaylemon_ops.sync_runs(captured_at DESC);

CREATE TABLE IF NOT EXISTS gaylemon_public.document_contents (
    sha256 text PRIMARY KEY,
    content jsonb NOT NULL,
    content_bytes bytea NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gaylemon_public.documents (
    path text PRIMARY KEY,
    sha256 text NOT NULL REFERENCES gaylemon_public.document_contents(sha256),
    cache_policy text NOT NULL CHECK (cache_policy IN ('no-store', 'revalidate', 'immutable')),
    generation_id text NOT NULL DEFAULT '',
    batch_id text NOT NULL REFERENCES gaylemon_ops.ingest_batches(batch_id),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS public_documents_generation_idx ON gaylemon_public.documents(generation_id) WHERE generation_id <> '';

CREATE TABLE IF NOT EXISTS gaylemon_ops.control_commands (
    command_id text PRIMARY KEY,
    agent_id text NOT NULL REFERENCES gaylemon_ops.agents(agent_id),
    sequence bigint GENERATED BY DEFAULT AS IDENTITY,
    kind text NOT NULL,
    arguments jsonb NOT NULL DEFAULT '{}'::jsonb,
    requested_by text NOT NULL,
    requested_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    acknowledged_at timestamptz,
    result_message text NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS control_commands_agent_pending_idx ON gaylemon_ops.control_commands(agent_id, sequence) WHERE status = 'pending';

CREATE TABLE IF NOT EXISTS gaylemon_ops.oauth_states (
    state_hash text PRIMARY KEY,
    verifier text NOT NULL,
    return_path text NOT NULL DEFAULT '/ops',
    expires_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS gaylemon_ops.sessions (
    token_hash text PRIMARY KEY,
    github_user_id bigint NOT NULL,
    github_login text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    expires_at timestamptz NOT NULL,
    last_seen_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS gaylemon_ops.audit_log (
    audit_id bigserial PRIMARY KEY,
    actor text NOT NULL,
    action text NOT NULL,
    target text NOT NULL DEFAULT '',
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS audit_log_created_at_idx ON gaylemon_ops.audit_log(created_at DESC);
