package web

const opsHTML = `<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Gaylémon — Exploitation</title>
  <style nonce="{{NONCE}}">
    :root{color-scheme:dark;--bg:#08130f;--panel:#10231b;--line:#28503d;--text:#ecfff5;--muted:#9fc4b2;--ok:#71e5a5;--warn:#ffd479;--bad:#ff8e8e}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#163326,var(--bg) 55%);color:var(--text);font:15px/1.5 system-ui,sans-serif}main{max-width:1180px;margin:auto;padding:32px 20px 64px}header{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:24px}h1{font-size:clamp(26px,5vw,44px);margin:0}p{color:var(--muted)}button,select,input{font:inherit}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:16px}.card{background:color-mix(in srgb,var(--panel) 92%,transparent);border:1px solid var(--line);border-radius:16px;padding:18px;box-shadow:0 18px 40px #0004}.metric{font-size:28px;font-weight:750}.muted{color:var(--muted)}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px 8px;border-bottom:1px solid var(--line);vertical-align:top}th{color:var(--muted);font-weight:600}.wide{grid-column:1/-1;overflow:auto}.actions,.control{display:flex;flex-wrap:wrap;gap:8px;align-items:center;margin:9px 0}button,select,input{border:1px solid var(--line);background:#173c2c;color:var(--text);border-radius:9px;padding:9px 13px}button{cursor:pointer}button:hover{background:#20533c}.danger{background:#582828;border-color:#9b4747}.status-success,.status-completed{color:var(--ok)}.status-failed,.status-refused{color:var(--bad)}code{color:#c7ffe0}#message{min-height:24px}.bar{height:7px;background:#183a2b;border-radius:6px;overflow:hidden}.bar span{display:block;height:100%;background:var(--ok)}@media(max-width:700px){header{align-items:flex-start;flex-direction:column}th:nth-child(4),td:nth-child(4){display:none}}
  </style>
</head>
<body><main>
  <header><div><h1>Exploitation Gaylémon</h1><p>Synchros, ressources et commandes du serveur.</p><p id="release" class="muted">Version en cours…</p></div><button id="logout">Déconnexion</button></header>
  <div id="message" class="muted"></div>
  <section class="grid">
    <article class="card"><div class="muted">Base de données</div><div class="metric" id="db">—</div></article>
    <article class="card"><div class="muted">Dernière actualisation</div><div class="metric" id="generated">—</div></article>
    <article class="card wide"><h2>Agents</h2><div id="agents"></div></article>
    <article class="card wide"><h2>Commandes</h2>
      <div class="control"><label for="stream">Flux</label><select id="stream"><option value="all">Tous</option><option value="metrics">Métriques</option><option value="stats">Statistiques</option><option value="events">Échos</option><option value="snapshot">Sauvegarde</option></select><button data-action="sync-run">Lancer</button><button data-action="sync-pause">Suspendre</button><button data-action="sync-resume">Reprendre</button><select id="schedule"><option>30s</option><option>1m</option><option selected>5m</option><option>30m</option><option>2h</option></select><button data-action="sync-schedule">Appliquer l'horaire</button></div>
      <div class="control"><label for="unit">Service</label><select id="unit"><option>gaylemon-agent.service</option><option>gaylemon-collect-metrics.service</option><option>gaylemon-collect-stats.service</option><option>gaylemon-publish-events.service</option><option>gaylemon-publish-snapshot.service</option><option>palworld-stats.service</option><option>palworld-events.service</option><option>palworld-save-snapshot.service</option></select><button data-action="logs">Voir les journaux</button><button data-action="restart" class="danger">Redémarrer</button></div>
      <div class="control"><input id="announcement" maxlength="240" size="48" placeholder="Message dans le chat du jeu"><button data-action="announce">Annoncer</button><button data-action="status">Actualiser le statut</button><button data-action="backup">Créer une sauvegarde</button></div>
      <div id="commands"></div></article>
    <article class="card wide"><h2>Exécutions récentes</h2><div id="runs"></div></article>
  </section>
</main>
<script nonce="{{NONCE}}">
const fmtBytes=n=>{if(!n)return '0 o';const u=['o','Ko','Mo','Go','To'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return n.toFixed(i?1:0)+' '+u[i]};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const csrf=()=>document.cookie.split('; ').find(v=>v.startsWith('gaylemon_csrf='))?.split('=').slice(1).join('=')||'';
let activeAgent='';
const sleep=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const shortResult=value=>{const text=String(value??'').trim();return text.length>260?text.slice(0,257)+'…':text};
const apiError=code=>({
  'recent-login-and-confirmation-required':'Reconnectez-vous à l’exploitation, puis confirmez de nouveau cette action.',
  'restart-arguments-refused':'Ce redémarrage n’est pas autorisé.',
  'command-refused':'Cette commande n’est pas autorisée.',
  'command-failed':'La commande n’a pas pu être enregistrée.'
}[code]||code||'Commande refusée.');
async function load(){const r=await fetch('/ops/api/snapshot',{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('Le tableau est indisponible.');const d=await r.json();document.querySelector('#db').textContent=fmtBytes(d.databaseBytes);document.querySelector('#generated').textContent=new Date(d.generatedAt).toLocaleTimeString('fr-CA');activeAgent=d.agents?.[0]?.agentId||'';document.querySelector('#agents').innerHTML=table(['Agent','Dernier contact','Profil','File','Erreur'],(d.agents||[]).map(a=>[a.agentId,new Date(a.lastSeenAt).toLocaleString('fr-CA'),a.profile,a.queueDepth,a.lastError]));document.querySelector('#runs').innerHTML=table(['Flux','Instant','Durée','CPU','Mémoire','Envoi','État'],(d.recentRuns||[]).map(x=>[x.stream,new Date(x.capturedAt).toLocaleString('fr-CA'),x.durationMs+' ms',x.cpuMs+' ms',fmtBytes(x.maxRssBytes),fmtBytes(x.bytesSent),x.status]));document.querySelector('#commands').innerHTML=table(['Commande','Agent','Demandée','État','Résultat'],(d.recentCommands||[]).map(x=>[x.kind,x.agentId,new Date(x.requestedAt).toLocaleString('fr-CA'),x.status,shortResult(x.message)]));return d;}
async function loadRelease(){const r=await fetch('/version',{cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok)throw new Error('Version indisponible.');const d=await r.json();const commit=/^[0-9a-f]{7,64}$/i.test(String(d.commit||''))?' · '+String(d.commit).slice(0,7):'';document.querySelector('#release').textContent='v'+String(d.version||'inconnue')+commit+' · '+String(d.channel||'non précisé');}
function table(headers,rows){return '<table><thead><tr>'+headers.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(x=>'<td>'+esc(x)+'</td>').join('')+'</tr>').join('')+'</tbody></table>'}
async function waitForCommand(id){for(let attempt=0;attempt<80;attempt++){const snapshot=await load();const current=(snapshot.recentCommands||[]).find(item=>item.id===id);if(current&&current.status!=='pending')return current;await sleep(1500)}throw new Error('La commande est toujours en cours. Son état continuera d’apparaître dans le tableau.');}
async function command(kind,args={},dangerous=false){if(!activeAgent)throw new Error('Aucun agent actif.');const body={agentId:activeAgent,kind,arguments:args};if(dangerous){const confirmation=prompt('Confirmer avec GAYLÉMON. La connexion doit dater de moins de cinq minutes.');if(confirmation!=='GAYLÉMON')throw new Error('Confirmation annulée.');body.confirm=confirmation}const r=await fetch('/ops/api/commands',{method:'POST',headers:{'Content-Type':'application/json','X-Gaylemon-CSRF':csrf()},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(apiError(d.error));document.querySelector('#message').textContent='Commande transmise, en attente du serveur…';const result=await waitForCommand(d.id);if(result.status!=='completed')throw new Error(shortResult(result.message)||'La commande a échoué.');document.querySelector('#message').textContent=shortResult(result.message)||'Commande terminée.';return result;}
const execute=fn=>fn().catch(e=>document.querySelector('#message').textContent=e.message);document.querySelector('[data-action="sync-run"]').onclick=()=>execute(()=>command('sync.run',{stream:document.querySelector('#stream').value}));document.querySelector('[data-action="sync-pause"]').onclick=()=>execute(()=>command('sync.pause',{stream:document.querySelector('#stream').value}));document.querySelector('[data-action="sync-resume"]').onclick=()=>execute(()=>command('sync.resume',{stream:document.querySelector('#stream').value}));document.querySelector('[data-action="sync-schedule"]').onclick=()=>execute(()=>{const stream=document.querySelector('#stream').value;if(stream==='all')throw new Error('Choisir un seul flux pour changer son horaire.');return command('sync.set-schedule',{stream,schedule:document.querySelector('#schedule').value})});document.querySelector('[data-action="logs"]').onclick=()=>execute(()=>command('server.logs',{unit:document.querySelector('#unit').value}));document.querySelector('[data-action="status"]').onclick=()=>execute(()=>command('server.status'));document.querySelector('[data-action="backup"]').onclick=()=>execute(()=>command('server.backup'));document.querySelector('[data-action="announce"]').onclick=()=>execute(()=>command('server.announce',{message:document.querySelector('#announcement').value}));document.querySelector('[data-action="restart"]').onclick=()=>{const unit=document.querySelector('#unit').value;execute(()=>command('service.restart',{unit},true))};
document.querySelector('#logout').addEventListener('click',async()=>{await fetch('/ops/auth/logout',{method:'POST',headers:{'X-Gaylemon-CSRF':csrf()}});location.href='/'});
loadRelease().catch(()=>document.querySelector('#release').textContent='Version indisponible');load().catch(e=>document.querySelector('#message').textContent=e.message);setInterval(()=>load().catch(()=>{}),15000);
</script></body></html>`
